# Postgres

development:
  adapter: postgresql
  database: roostats_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: roostats_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: roostats_production
  pool: 5
  timeout: 5000
